const translations = {
    fr: {
        // --- COMMUN ---
        btn_back_arrow: "◀ RETOUR",

        // --- PAGE ACCUEIL ---
        label_gate: "PORTE",
        status_open: "OUVERTE",
        status_closed: "FERMÉE",
        next_open: "PROCHAINE OUVERTURE",
        next_close: "PROCHAINE FERMETURE",
        high_tide: "PLEINE MER",
        low_tide: "BASSE MER",
        height: "Hauteur",
        coeff: "Coef.",
        btn_planning: "PORTES & MARÉES",
        btn_share: "PARTAGER",
        btn_security: "🆘 SÉCURITÉ ET RAPPEL",
        btn_partners: "🤝 NOS PARTENAIRES",
        btn_links: "⚓ LIENS UTILES",
        btn_contact: "✉️ NOUS CONTACTER",
        footer_title: "Plus d'informations",
        today: "Aujourd'hui",
        tomorrow: "Demain",

        // --- PAGE SÉCURITÉ ---
        secu_title: "Sécurité & Rappels",
        secu_cross_title: "Secours en mer (CROSS)",
        secu_vhf: "VHF CANAL 16",
        secu_direct_line: "Ligne directe CROSS Manche",
        secu_other_services: "Autres Services",
        secu_semaphore: "Sémaphore",
        secu_fire: "Pompiers",
        secu_medical: "SAMU",
        secu_speed_title: "Limitation de vitesse",
        secu_speed_text: "• <span class=\"highlight\">3 nœuds</span> dans la zone du bassin à flot.<br>• <span class=\"highlight\">5 nœuds</span> dans la partie marnante.",
        secu_current_title: "⚠️ Courant à la porte",
        secu_current_text: "À l’ouverture de la porte, un <span class=\"highlight\">fort courant</span> peut se produire pendant 15 à 30 min (selon les coefficients). Soyez vigilant lors du passage !",
        secu_precision_title: "Précisions horaires",
        secu_precision_text1: "Les heures sont exprimées en <span style=\"font-weight:700;\">heure légale française</span>.",
        secu_precision_text2: "Des fluctuations de <span class=\"highlight\">+/- 30 min</span> peuvent survenir (pression, vent, coefficients). Ces données sont indicatives et n'engagent pas la responsabilité du Port.",

        // --- PAGE LIENS ---
        links_subtitle: "RESOURCES & LIENS UTILES",
        links_shom_title: "📏 SHOM",
        links_shom_desc: "Référence officielle pour les prédictions de marées et la cartographie marine.",
        links_shom_btn: "ACCÉDER AU SHOM",
        links_navco_title: "📱 Nav&Co",
        links_navco_desc: "L'application officielle pour naviguer en sécurité tout en découvrant la biodiversité marine.",
        links_navco_btn: "DÉCOUVRIR NAV&CO",
        links_secu_title: "⚠️ Sécurité en mer",
        links_secu_desc: "Rappel officiel des règles de sécurité pour les loisirs nautiques (mer.gouv.fr).",
        links_secu_btn: "LIRE LES RÈGLES",
        links_snsm_title: "🧡 SNSM Carteret",
        links_snsm_desc: "Soutenez les sauveteurs en mer de la station locale et informez-vous sur le sauvetage.",
        links_snsm_btn: "STATION SNSM",
        links_meteo_title: "☁️ Météo - Prévisions Barneville Carteret",
        links_meteo_desc: "Bulletins côtiers détaillés.",
        links_meteo_btn: "CONSULTER LA MÉTÉO",
        links_disclaimer: "<strong style=\"color:#b03a2e;\">* Attention :</strong> Ces liens sont externes. L'éditeur n'est pas responsable de leur contenu.",

        // --- PAGE PARTAGE ---
        share_title: "Partagez l'application",
        share_desc: "Faites scanner ce QR Code à un autre marin pour qu'il accède directement aux horaires du port."
    },
    en: {
        // --- COMMUN ---
        btn_back_arrow: "◀ BACK",

        // --- PAGE ACCUEIL ---
        label_gate: "GATE",
        status_open: "OPEN",
        status_closed: "CLOSED",
        next_open: "NEXT OPENING",
        next_close: "NEXT CLOSING",
        high_tide: "HIGH TIDE",
        low_tide: "LOW TIDE",
        height: "Height",
        coeff: "Coeff.",
        btn_planning: "GATE & TIDE",
        btn_share: "SHARE",
        btn_security: "🆘 SAFETY & RULES",
        btn_partners: "🤝 OUR PARTNERS",
        btn_links: "⚓ USEFUL LINKS",
        btn_contact: "✉️ CONTACT US",
        footer_title: "More information",
        today: "Today",
        tomorrow: "Tomorrow",

        // --- PAGE SÉCURITÉ ---
        secu_title: "Safety & Rules",
        secu_cross_title: "Sea Rescue (CROSS)",
        secu_vhf: "VHF CHANNEL 16",
        secu_direct_line: "CROSS Manche direct line",
        secu_other_services: "Other Services",
        secu_semaphore: "Semaphore",
        secu_fire: "Fire Dept",
        secu_medical: "Ambulance",
        secu_speed_title: "Speed limit",
        secu_speed_text: "• <span class=\"highlight\">3 knots</span> in the wet dock area.<br>• <span class=\"highlight\">5 knots</span> in the tidal area.",
        secu_current_title: "⚠️ Current at the gate",
        secu_current_text: "When the gate opens, a <span class=\"highlight\">strong current</span> can occur for 15 to 30 mins (depending on coefficients). Please be extremely vigilant when passing through!",
        secu_precision_title: "Time accuracy",
        secu_precision_text1: "Times are expressed in <span style=\"font-weight:700;\">French legal time</span>.",
        secu_precision_text2: "Fluctuations of <span class=\"highlight\">+/- 30 mins</span> may occur (pressure, wind, coefficients). This data is indicative and the Port assumes no liability.",

        // --- PAGE LIENS ---
        links_subtitle: "RESOURCES & USEFUL LINKS",
        links_shom_title: "📏 SHOM",
        links_shom_desc: "Official reference for tide predictions and marine cartography.",
        links_shom_btn: "ACCESS SHOM",
        links_navco_title: "📱 Nav&Co",
        links_navco_desc: "The official app to navigate safely while discovering marine biodiversity.",
        links_navco_btn: "DISCOVER NAV&CO",
        links_secu_title: "⚠️ Sea Safety",
        links_secu_desc: "Official safety rules for nautical activities (mer.gouv.fr).",
        links_secu_btn: "READ THE RULES",
        links_snsm_title: "🧡 SNSM Carteret",
        links_snsm_desc: "Support the local sea rescue station and learn more about sea rescue.",
        links_snsm_btn: "SNSM STATION",
        links_meteo_title: "☁️ Weather - Barneville Carteret Forecast",
        links_meteo_desc: "Detailed coastal weather reports.",
        links_meteo_btn: "CHECK WEATHER",
        links_disclaimer: "<strong style=\"color:#b03a2e;\">* Warning:</strong> These are external links. The publisher is not responsible for their content.",

        // --- PAGE PARTAGE ---
        share_title: "Share the application",
        share_desc: "Have another sailor scan this QR Code to directly access the port schedules.",
        // --- PAGE CONTACT ---
        contact_title: "Une question ou un projet ?",
        contact_desc: "Vous êtes commerçant et souhaitez apparaître sur l'application ? Ou vous avez simplement une suggestion ? Contactez-moi directement :",
        contact_btn_email: "📧 Par E-mail",
        contact_footer_text: "Application développée avec passion pour les marins du Cotentin. ⚓",
        contact_disclaimer: "<strong style=\"color:#b03a2e;\">*Attention :</strong> Pour toute urgence en mer, contactez le <strong>196</strong> ou le canal <strong>VHF 16</strong>.",
        contact_ns: "Nous contacter",
        // --- PAGE CONTACT ---
        contact_title: "A question or a project?",
        contact_desc: "Are you a local business owner who wants to be featured in the app? Or do you simply have a suggestion? Contact me directly:",
        contact_btn_email: "📧 By Email",
        contact_footer_text: "App developed with passion for the sailors of Cotentin. ⚓",
        contact_disclaimer: "<strong style=\"color:#b03a2e;\">*Warning:</strong> For any emergency at sea, contact <strong>196</strong> or <strong>VHF channel 16</strong>.",
        contact_ns: "Contact us",
    }
};
