const translations = {
    fr: {
        // --- COMMUN ---
        btn_back_arrow: "◀ RETOUR",
// --- NOUVEAUTÉS PAGE PARTAGE ---
        // --- Page Sécurité ---
"desc_maison_renard": "Pains spéciaux, macarons, nos meilleurs chocolats et pâtisseries artisanales.",
"time_maison_renard": "⏱️ Sponsor de 07h00 à 08h00",
    "secu_title": "Sécurité & Rappels",
    "secu_cross_title": "Secours en mer (CROSS)",
    "secu_vhf": "VHF CANAL 16",
    "secu_direct_line": "Ligne directe CROSS Manche",
    "secu_other_services": "Autres Services",
    "secu_semaphore": "Sémaphore",
    "secu_fire": "Pompiers",
    "secu_medical": "SAMU",
    "secu_equip_title": "Équipement de sécurité",
    "secu_equip_text": "Vérifiez le matériel d'armement et de sécurité obligatoire pour votre navire selon votre zone de navigation avant de prendre la mer.",
    "secu_equip_btn": "📄 GUIDE OFFICIEL MARS 2025",
    "secu_speed_title": "Limitation de vitesse",
    "secu_speed_text": "• <span class=\"highlight\">3 nœuds</span> dans la zone du bassin à flot.<br>• <span class=\"highlight\">5 nœuds</span> dans la partie marnante.",
    "secu_current_title": "⚠️ Courant à la porte",
    "secu_current_text": "À l’ouverture de la porte, un <span class=\"highlight\">fort courant</span> peut se produire pendant 15 à 30 min (selon les coefficients). Soyez vigilant lors du passage !",
    "secu_resp_title": "Responsabilité du Capitaine",
    "secu_resp_text1": "Le chef de bord est l'unique responsable de la conduite de son navire, de la sécurité de son équipage et du respect de la réglementation en vigueur.",
    "secu_resp_text2": "Les informations fournies par cette application sont purement indicatives. L'éditeur décline toute responsabilité en cas d'erreur ou d'incident survenu suite à l'utilisation de ces données. Seuls les documents et signaux officiels font foi.",
        sponsor_label: "PARTENAIRES",
        btn_webcam: "📷 WEBCAM",
        webcam_main_title: "WEBCAM EN DIRECT",
    webcam_module_title: "Vue du chenal",
    webcam_desc: "Observez les conditions en temps réel à l'entrée du port de Barneville-Carteret.",
    webcam_disclaimer: "<strong style=\"color:#b03a2e;\">* Attention :</strong> Le flux vidéo est fourni à titre indicatif par Viewsurf et peut subir des décalages.",
        sponsor_utile: "🛒 UTILE Barneville-Carteret - Alimentation, Dépôt de pain & Livraison",
    sponsor_or_coiffure: "✂️ L'Or Coiffure - Salon de coiffure",
    sponsor_carteret_marine: "🛥️ Carteret Marine - Rénovation, achat et accessoires nautiques",
    sponsor_la_cambuse: "🍽️ La Cambuse - Traiteur salé & sucré",
    sponsor_esprit_marin: "🛍️ Esprit Marin - Concept store sport chic & Déco",
    sponsor_delizia: "🍔 Deliziafoodtruck, Cuisine Italienne - ",
    sponsor_default: "⚓ Votre publicité ici ! Cliquez pour nous contacter.",
    loc_service: "En service !",
    loc_denneville: "Aujourd'hui à Denneville",
    loc_portbail: "Aujourd'hui à Port-Bail",
    loc_barneville_flandres: "Aujourd'hui pl. Flandres (Barneville)",
    loc_pieux: "Aujourd'hui aux Pieux",
    loc_barneville_ecoles: "Aujourd'hui rue des Écoles (Barneville)",
        share_link_title: "Envoyer le lien",
        share_link_desc: "Envoyez l'application directement à vos amis par SMS, WhatsApp, Signal ou E-mail.",
        share_btn_text: "📤 Partager l'application",
        share_copied: "Lien copié dans le presse-papier !",
        slot_current: "Créneaux officiels",
        slot_next: "Prochains créneaux",
        // --- PAGE ACCUEIL ---
        label_gate: "PORTE",
        status_open: "OUVERTE",
        status_closed: "FERMÉE",
        next_open: "PROCHAINE OUVERTURE",
        next_close: "PROCHAINE FERMETURE",
        high_tide: "PLEINE MER",
        low_tide: "BASSE MER",
        height: "Hauteur",
        coeff: "Coef.",
        btn_planning: "PORTES & MARÉES",
        btn_share: "PARTAGER",
        btn_security: "🆘 SÉCURITÉ ET RAPPEL",
        btn_partners: "🤝 NOS PARTENAIRES",
        btn_links: "⚓ LIENS UTILES",
        btn_contact: "✉️ NOUS CONTACTER",
        footer_title: "Plus d'informations",
        today: "Aujourd'hui",
        tomorrow: "Demain",
        install_title: "Installer sur l'écran d'accueil",
install_desc: "Ajoutez un raccourci sur votre téléphone pour y accéder en un clic, comme une vraie application !",
install_ios_title: "🍎 Sur iPhone (iOS)",
install_ios_step1: "Ouvrez ce site avec l'application <b>Safari</b>.",
install_ios_step2: "Appuyez sur l'icône <b>Partage</b> <span style=\"font-size: 0.9em;\">(le carré avec une flèche vers le haut)</span> en bas de l'écran.",
install_ios_step3: "Faites défiler et choisissez <b>\"Sur l'écran d'accueil\"</b> <span style=\"font-size: 0.9em;\">(le carré avec un +)</span>.",
install_ios_step4: "Appuyez sur <b>Ajouter</b> en haut à droite.",
install_android_title: "🤖 Sur Android",
install_android_step1: "Ouvrez ce site avec l'application <b>Chrome</b>.",
install_android_step2: "Appuyez sur le <b>Menu</b> <span style=\"font-size: 0.9em;\">(les 3 petits points verticaux)</span> en haut à droite.",
install_android_step3: "Choisissez <b>\"Ajouter à l'écran d'accueil\"</b> ou <b>\"Installer l'application\"</b>.",
install_android_step4: "Appuyez sur <b>Ajouter</b>.",
        partners_title: "NOS PARTENAIRES LOCAUX",
desc_or_coiffure: "Salon de coiffure.",
time_or_coiffure: "⏱️ Sponsor de 09h00 à 10h00",
desc_carteret_marine: "Accompagnement, rénovation, achat et accessoires nautiques.",
time_carteret_marine: "⏱️ Sponsor de 10h00 à 11h00",
desc_la_cambuse: "Boutique traiteur salé et sucré.",
time_la_cambuse: "⏱️ Sponsor de 11h00 à 12h00",
desc_esprit_marin: "Concept store : mode sport chic, déco et produits locaux/made in France.",
time_esprit_marin: "⏱️ Sponsor de 14h00 à 15h00",
become_partner_title: "Devenez Partenaire",
become_partner_desc: "Soutenez l'application et affichez votre enseigne sur l'application web.",
btn_call: "📞 APPELER",
btn_directions: "📍 ITINÉRAIRE",
btn_website: "🌐 SITE WEB",
btn_email: "✉️ E-MAIL",
btn_contact_us: "NOUS CONTACTER",
disclaimer_partners: "<strong style=\"color:#b03a2e;\">*Attention :</strong> L'éditeur décline toute responsabilité en cas d'erreur.",
        // --- PAGE PLANNING ---
        plan_scroll_hint: "👉 Glissez le tableau vers la gauche pour voir le SOIR",
        plan_date: "Date",
        plan_morning: "☀️ MATIN",
        plan_evening: "🌙 SOIR",
        plan_gate_col: "Porte (Ouv | Ferm)",
        plan_high_tide: "Pleine Mer",
        plan_low_tide: "Basse Mer",
        plan_coeff: "Coeff",
        // --- NOUVEAUTÉS PAGE INDEX ---
        slots_title: "Créneaux officiels :",
        tide_title: "Informations marée",
        weather_title: "Conditions météo",
        index_disclaimer: "<strong style=\"color:#b03a2e;\">* Attention :</strong> Les horaires peuvent varier selon météo et marée (+/- 30 min). Chenalage à prévoir inférieur à 10 minutes. Toutes les données du site sont à titre indicatif. L'éditeur décline toute responsabilité en cas d'erreur. Le capitaine est responsable de sa navigation.",
        time_before_close: " avant fermeture",
        time_opening_in: "Ouverture dans ",
        status_imminent: "IMMINENTE",
        label_closing: "FERMETURE",
        pill_open: "OUV.",
        pill_close: "FERM.",

        // --- PAGE SÉCURITÉ ---
        secu_title: "Sécurité & Rappels",
        secu_cross_title: "Secours en mer (CROSS)",
        secu_vhf: "VHF CANAL 16",
        secu_direct_line: "Ligne directe CROSS Manche",
        secu_other_services: "Autres Services",
        secu_semaphore: "Sémaphore",
        secu_fire: "Pompiers",
        secu_medical: "SAMU",
        secu_speed_title: "Limitation de vitesse",
        secu_speed_text: "• <span class=\"highlight\">3 nœuds</span> dans la zone du bassin à flot.<br>• <span class=\"highlight\">5 nœuds</span> dans la partie marnante.",
        secu_current_title: "⚠️ Courant à la porte",
        secu_current_text: "À l’ouverture de la porte, un <span class=\"highlight\">fort courant</span> peut se produire pendant 15 à 30 min (selon les coefficients). Soyez vigilant lors du passage !",
        secu_precision_title: "Précisions horaires",
        secu_precision_text1: "Les heures sont exprimées en <span style=\"font-weight:700;\">heure légale française</span>.",
        secu_precision_text2: "Des fluctuations de <span class=\"highlight\">+/- 30 min</span> peuvent survenir (pression, vent, coefficients). Ces données sont indicatives et n'engagent pas la responsabilité du Port.",

        // --- PAGE LIENS ---
        links_subtitle: "RESOURCES & LIENS UTILES",
        links_shom_title: "📏 SHOM",
        links_shom_desc: "Référence officielle pour les prédictions de marées et la cartographie marine.",
        links_shom_btn: "ACCÉDER AU SHOM",
        links_navco_title: "📱 Nav&Co",
        links_navco_desc: "L'application officielle pour naviguer en sécurité tout en découvrant la biodiversité marine.",
        links_navco_btn: "DÉCOUVRIR NAV&CO",
        links_secu_title: "⚠️ Sécurité en mer",
        links_secu_desc: "Rappel officiel des règles de sécurité pour les loisirs nautiques (mer.gouv.fr).",
        links_secu_btn: "LIRE LES RÈGLES",
        links_snsm_title: "🧡 SNSM Carteret",
        links_snsm_desc: "Soutenez les sauveteurs en mer de la station locale et informez-vous sur le sauvetage.",
        links_snsm_btn: "STATION SNSM",
        links_meteo_title: "☁️ Météo - Prévisions Barneville Carteret",
        links_meteo_desc: "Bulletins côtiers détaillés.",
        links_meteo_btn: "CONSULTER LA MÉTÉO",
        links_disclaimer: "<strong style=\"color:#b03a2e;\">* Attention :</strong> Ces liens sont externes. L'éditeur n'est pas responsable de leur contenu.",

        // --- PAGE PARTAGE ---
        share_title: "Partagez l'application",
        share_desc: "Faites scanner ce QR Code à un autre marin pour qu'il accède directement aux horaires du port."
    },
    en: {
        // --- COMMUN ---
        btn_back_arrow: "◀ BACK",
// --- NOUVEAUTÉS PAGE PARTAGE ---
        // --- Security Page ---
"desc_maison_renard": "Specialty breads, macarons, our finest chocolates and artisanal pastries.",
"time_maison_renard": "⏱️ Sponsor from 7:00 AM to 8:00 AM",
    "secu_title": "Safety & Guidelines",
    "secu_cross_title": "Sea Rescue (CROSS)",
    "secu_vhf": "VHF CHANNEL 16",
    "secu_direct_line": "Direct line CROSS Manche",
    "secu_other_services": "Other Services",
    "secu_semaphore": "Semaphore",
    "secu_fire": "Fire Dept",
    "secu_medical": "Ambulance",
    "secu_equip_title": "Safety Equipment",
    "secu_equip_text": "Check the mandatory safety and armament equipment for your vessel according to your navigation area before setting sail.",
    "secu_equip_btn": "📄 OFFICIAL GUIDE MAR 2025",
    "secu_speed_title": "Speed Limit",
    "secu_speed_text": "• <span class=\"highlight\">3 knots</span> in the wet dock area.<br>• <span class=\"highlight\">5 knots</span> in the tidal area.",
    "secu_current_title": "⚠️ Gate Current",
    "secu_current_text": "When the gate opens, a <span class=\"highlight\">strong current</span> can occur for 15 to 30 mins (depending on coefficients). Be careful when passing through!",
    "secu_resp_title": "Captain's Responsibility",
    "secu_resp_text1": "The skipper is solely responsible for navigating their vessel, ensuring the safety of the crew, and complying with current regulations.",
    "secu_resp_text2": "The information provided by this application is purely indicative. The publisher declines all responsibility for any error or incident arising from the use of this data. Only official documents and signals are legally binding.",
        sponsor_label: "PARTNERS",
        btn_webcam: "📷 WEBCAM",
        webcam_main_title: "LIVE WEBCAM",
    webcam_module_title: "Channel View",
    webcam_desc: "Check the real-time conditions at the entrance of Barneville-Carteret port.",
    webcam_disclaimer: "<strong style=\"color:#b03a2e;\">* Warning:</strong> The video feed is provided for informational purposes by Viewsurf and may experience delays.",
        sponsor_utile: "🛒 UTILE Barneville-Carteret - Groceries, Bakery & Delivery",
    sponsor_or_coiffure: "✂️ L'Or Coiffure - Hair Salon",
    sponsor_carteret_marine: "🛥️ Carteret Marine - Boat renovation, sales & accessories",
    sponsor_la_cambuse: "🍽️ La Cambuse - Sweet & savory catering",
    sponsor_esprit_marin: "🛍️ Esprit Marin - Sport chic concept store & Deco",
    sponsor_delizia: "🍔 Deliziafoodtruck, Italian Food - ",
    sponsor_default: "⚓ Your ad here! Click to contact us.",
    loc_service: "In service!",
    loc_denneville: "Today in Denneville",
    loc_portbail: "Today in Port-Bail",
    loc_barneville_flandres: "Today at Flandres sq. (Barneville)",
    loc_pieux: "Today in Les Pieux",
    loc_barneville_ecoles: "Today at Écoles st. (Barneville)",
        share_link_title: "Send the link",
        share_link_desc: "Send the app directly to your friends via SMS, WhatsApp, Signal, or Email.",
        share_btn_text: "📤 Share the app",
        share_copied: "Link copied to clipboard!",
        slot_current: "Official Slots:",
        slot_next: "Next Slots:",
        // --- PAGE ACCUEIL ---
        label_gate: "GATE",
        status_open: "OPEN",
        status_closed: "CLOSED",
        next_open: "NEXT OPENING",
        next_close: "NEXT CLOSING",
        high_tide: "HIGH TIDE",
        low_tide: "LOW TIDE",
        height: "Height",
        coeff: "Coeff.",
        btn_planning: "GATE & TIDE",
        btn_share: "SHARE",
        btn_security: "🆘 SAFETY & RULES",
        btn_partners: "🤝 OUR PARTNERS",
        btn_links: "⚓ USEFUL LINKS",
        btn_contact: "✉️ CONTACT US",
        footer_title: "More information",
        today: "Today",
        tomorrow: "Tomorrow",
        // --- PAGE PLANNING ---
        plan_scroll_hint: "👉 Swipe the table left to see the EVENING",
        plan_date: "Date",
        plan_morning: "☀️ MORNING",
        plan_evening: "🌙 EVENING",
        plan_gate_col: "Gate (Open|Close)",
        plan_high_tide: "High Tide",
        plan_low_tide: "Low Tide",
        plan_coeff: "Coeff",
        install_title: "Install on Home Screen",
install_desc: "Add a shortcut to your phone to access it in one click, just like a real app!",
install_ios_title: "🍎 On iPhone (iOS)",
install_ios_step1: "Open this site with the <b>Safari</b> app.",
install_ios_step2: "Tap the <b>Share</b> icon <span style=\"font-size: 0.9em;\">(the square with an up arrow)</span> at the bottom of the screen.",
install_ios_step3: "Scroll down and select <b>\"Add to Home Screen\"</b> <span style=\"font-size: 0.9em;\">(the square with a +)</span>.",
install_ios_step4: "Tap <b>Add</b> in the top right corner.",
install_android_title: "🤖 On Android",
install_android_step1: "Open this site with the <b>Chrome</b> app.",
install_android_step2: "Tap the <b>Menu</b> <span style=\"font-size: 0.9em;\">(the 3 vertical dots)</span> in the top right corner.",
install_android_step3: "Select <b>\"Add to Home screen\"</b> or <b>\"Install app\"</b>.",
install_android_step4: "Tap <b>Add</b>.",
        partners_title: "OUR LOCAL PARTNERS",
desc_or_coiffure: "Hair salon.",
time_or_coiffure: "⏱️ Sponsor from 09:00 to 10:00",
desc_carteret_marine: "Support, renovation, purchase and nautical accessories.",
time_carteret_marine: "⏱️ Sponsor from 10:00 to 11:00",
desc_la_cambuse: "Sweet and savory deli shop.",
time_la_cambuse: "⏱️ Sponsor from 11:00 to 12:00",
desc_esprit_marin: "Concept store: sport chic fashion, decor and local/made in France products.",
time_esprit_marin: "⏱️ Sponsor from 14:00 to 15:00",
become_partner_title: "Become a Partner",
become_partner_desc: "Support the app and display your brand on the web application.",
btn_call: "📞 CALL",
btn_directions: "📍 DIRECTIONS",
btn_website: "🌐 WEBSITE",
btn_email: "✉️ E-MAIL",
btn_contact_us: "CONTACT US",
disclaimer_partners: "<strong style=\"color:#b03a2e;\">*Warning:</strong> The publisher declines all responsibility in case of error.",
// --- NOUVEAUTÉS PAGE INDEX ---
        slots_title: "Official slots:",
        tide_title: "Tide information",
        weather_title: "Weather conditions",
        index_disclaimer: "<strong style=\"color:#b03a2e;\">* Warning:</strong> Times may vary depending on weather and tide (+/- 30 min). Approach channel time is under 10 minutes. All data on this site is indicative. The publisher declines all responsibility in the event of an error. The captain is responsible for their navigation.",
        time_before_close: " before closing",
        time_opening_in: "Opening in ",
        status_imminent: "IMMINENT",
        label_closing: "CLOSING",
        pill_open: "OPEN",
        pill_close: "CLOSE",
        // --- PAGE SÉCURITÉ ---
        secu_title: "Safety & Rules",
        secu_cross_title: "Sea Rescue (CROSS)",
        secu_vhf: "VHF CHANNEL 16",
        secu_direct_line: "CROSS Manche direct line",
        secu_other_services: "Other Services",
        secu_semaphore: "Semaphore",
        secu_fire: "Fire Dept",
        secu_medical: "Ambulance",
        secu_speed_title: "Speed limit",
        secu_speed_text: "• <span class=\"highlight\">3 knots</span> in the wet dock area.<br>• <span class=\"highlight\">5 knots</span> in the tidal area.",
        secu_current_title: "⚠️ Current at the gate",
        secu_current_text: "When the gate opens, a <span class=\"highlight\">strong current</span> can occur for 15 to 30 mins (depending on coefficients). Please be extremely vigilant when passing through!",
        secu_precision_title: "Time accuracy",
        secu_precision_text1: "Times are expressed in <span style=\"font-weight:700;\">French legal time</span>.",
        secu_precision_text2: "Fluctuations of <span class=\"highlight\">+/- 30 mins</span> may occur (pressure, wind, coefficients). This data is indicative and the Port assumes no liability.",

        // --- PAGE LIENS ---
        links_subtitle: "RESOURCES & USEFUL LINKS",
        links_shom_title: "📏 SHOM",
        links_shom_desc: "Official reference for tide predictions and marine cartography.",
        links_shom_btn: "ACCESS SHOM",
        links_navco_title: "📱 Nav&Co",
        links_navco_desc: "The official app to navigate safely while discovering marine biodiversity.",
        links_navco_btn: "DISCOVER NAV&CO",
        links_secu_title: "⚠️ Sea Safety",
        links_secu_desc: "Official safety rules for nautical activities (mer.gouv.fr).",
        links_secu_btn: "READ THE RULES",
        links_snsm_title: "🧡 SNSM Carteret",
        links_snsm_desc: "Support the local sea rescue station and learn more about sea rescue.",
        links_snsm_btn: "SNSM STATION",
        links_meteo_title: "☁️ Weather - Barneville Carteret Forecast",
        links_meteo_desc: "Detailed coastal weather reports.",
        links_meteo_btn: "CHECK WEATHER",
        links_disclaimer: "<strong style=\"color:#b03a2e;\">* Warning:</strong> These are external links. The publisher is not responsible for their content.",

        // --- PAGE PARTAGE ---
        share_title: "Share the application",
        share_desc: "Have another sailor scan this QR Code to directly access the port schedules.",
        // --- PAGE CONTACT ---
        contact_title: "Une question ou un projet ?",
        contact_desc: "Vous êtes commerçant et souhaitez apparaître sur l'application ? Ou vous avez simplement une suggestion ? Contactez-moi directement :",
        contact_btn_email: "📧 Par E-mail",
        contact_footer_text: "Application développée avec passion pour les marins du Cotentin. ⚓",
        contact_disclaimer: "<strong style=\"color:#b03a2e;\">*Attention :</strong> Pour toute urgence en mer, contactez le <strong>196</strong> ou le canal <strong>VHF 16</strong>.",
        contact_ns: "Nous contacter",
        // --- PAGE CONTACT ---
        contact_title: "A question or a project?",
        contact_desc: "Are you a local business owner who wants to be featured in the app? Or do you simply have a suggestion? Contact me directly:",
        contact_btn_email: "📧 By Email",
        contact_footer_text: "App developed with passion for the sailors of Cotentin. ⚓",
        contact_disclaimer: "<strong style=\"color:#b03a2e;\">*Warning:</strong> For any emergency at sea, contact <strong>196</strong> or <strong>VHF channel 16</strong>.",
        contact_ns: "Contact us",
    }
};
